import "./globals.css";
import {Montserrat} from "@next/font/google";

const monstserrat = Montserrat({
  weight: ["400"],
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body className={`${monstserrat.className}`}>
        <nav>
          <h1>logo</h1>
          <ul>
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Portfolio</a>
            </li>
            <li>
              <a href="#">Resume</a>
            </li>
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
        </nav>
        {children}

        <footer>footer</footer>
      </body>
    </html>
  );
}
